### PR TITLE
Improving docs for pagination and sort

### PR DESCRIPTION
**Pull request by david-bc**
In response to #599

### CODE REVIEW

**Comment by typicode** [comment]
Hi @david-bc,

Thank you for the PR, seems that the current version is case insensitive.

I've added a test to be sure:
https://github.com/typicode/json-server/blob/f56624eb714cfc7f9023688e144376e6c0cd87a3/test/server/plural.js#L245

**Comment by david-bc** [comment]
Not in the live version:

http://jsonplaceholder.typicode.com/posts?_sort=id&_order=desc

http://jsonplaceholder.typicode.com/posts?_sort=id&_order=DESC

Good luck!

**Comment by typicode** [comment]
I see 👍 JSONPlaceholder is a little behind, it needs to be updated.

**Comment by typicode** [comment]
JSONPlaceholder have been updated ;)

**Pull request closed without merging**
