### PR TITLE
Expanded nested calls

### PR DESCRIPTION
**Pull request by therebelrobot**
Refer: https://github.com/typicode/json-server/issues/72#issuecomment-99582223

@isaacrg > Added as a PR because of https://github.com/typicode/json-server/issues/72#issuecomment-100673785

I am currently sourcing https://github.com/therebelrobot/json-server-nested in my work project, it has everything here except the most recent upstream merge for status code changes.

### CODE REVIEW

**Comment by isaacrg** [comment]
This looks awesome.


@typicode, what are your thoughts?

**Comment by typicode** [comment]
Hmm, honestly it's a hard choice and I'm not sure about it.
Also the PR is impressive, it's really cool work.

@isaacrg if you need it, support can easily be added using the project as a module and middlewares.

I've stumbled on projects like [express-rewrite](https://github.com/joehewitt/express-rewrite):

```javascript
// Would rewrite /categories/1/posts/1/comments to /posts/1/comments
server.get('/:a/:b/:parent/:parentId/:resource', rewriter.rewrite('/$3/$4/$5')
```

There's also [express-redirect](https://github.com/buschtoens/express-redirect) that seems to be an easy solution too.

**Comment by isaacrg** [comment]
@typicode Awesome - thanks for the find. I entirely understand if you don't want to PR this stuff, I get that you may well want to keep the library simple.

**Comment by typicode** [comment]
Well let's keep it simple then :) Closing it.

I was thinking also about maybe "json-server" specific middlewares, something that you could add like `server.use(extra(dbObject))`. A fork is a good idea too if you need more freedom.

**Comment by kuitos** [comment]
@therebelrobot awesome, that what I want !!  I will try it now

**Comment by isaacrg** [comment]
@therebelrobot Awesome work

**Pull request closed without merging**
