### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by striezel**
This pull request updates several dependencies to fix known security issues with those dependencies.

### CODE REVIEW

**Comment by striezel** [comment]
@typicode
Since nothing has happened here for a month, I have to ask: Is anything wrong with this pull request? If that is the case, then please let me know and I will try to fix it.

I _am_ aware of the fact that the AppVeyor check is failing for this PR, but it is also failing for the current latest commit on the master branch (see https://ci.appveyor.com/project/typicode/json-server/builds/36335391). Since it fails with the very same error, I assume that this PR does not introduce any regression.

**Comment by typicode** [comment]
Thanks for the fixes :+1:

**Comment by typicode** [comment]
And sorry for the late reply.

**Comment by striezel** [comment]
Thanks for merging these changes. :+1:

Seeing that you also updated some other dependencies yourself you might want to consider publishing a new version of the package to NPM.

**Pull request merged**
