### PR TITLE
Build: Fix tests (make eslint pretty)

### PR DESCRIPTION
**Pull request by bo01ean**
Build was failing, due to ESLINT bombing out over some formatting.
So I fixed it up.

---
This change is [Reviewable](https://reviewable.io/reviews/typicode/json-server/657)

### CODE REVIEW

**Comment by typicode** [comment]
Thank you for the PR!

I've noticed it, but it seems like it's mutually exclusive.
If it's fixed on Node 4, it fails on Node 8 (like in this PR) and if it's fixed on Node 8 then with Node 4 it fails.

I don't understand why :/

**Comment by typicode** [comment]
Maybe upgrading eslint or prettier to the latest version would help, but I'm not sure.

**Comment by bo01ean** [comment]
This is passing on node7 ... but the buold is running a 0.x.x release I'll look into a fix for all. I like the idea of bumping pretty/eslint, hopefully this isn't a bug there ;)

**Comment by typicode** [comment]
Fixed in https://github.com/typicode/json-server/pull/674
Seems like updating dependencies was enough.

Thanks for the help :)

**Pull request closed without merging**
