### PR TITLE
add 'afterware' to modify response

### PR DESCRIPTION
**Pull request by zsalzbank**
Allow response modification from the command line rather than having to write out the whole server as indicated in #118, #126, #266 and others.

### CODE REVIEW

**Comment by phoewass** [comment]
Great feature!
Hi @typicode what stops this PR from being merged ?

**Comment by phoewass** [comment]
@typicode any chance this PR gets reviewed ?

**Comment by zsalzbank** [comment]
A bit stale.

**Comment by adyz** [comment]
Hi!

Awesome piece of software works great for most cases except that I need the feature specified in this PR.

Why is this closed? Is it merged?  @zsalzbank did you make a fork that I can use from npm with your changes?

🙏

**Comment by zsalzbank** [comment]
No, sorry.

**Comment by adyz** [comment]
Ah, no problem. Thank you for the quick response.


I managed to get the result I wanted using a custom server.js file as written here:


https://github.com/typicode/json-server#custom-output-example


```js
// server.js
const path = require('path')
const jsonServer = require('json-server')
const server = jsonServer.create()
const router = jsonServer.router(path.join(__dirname, 'db.json'))
const middlewares = jsonServer.defaults()

server.use(middlewares)
server.use(router)
server.listen(3333, () => {
  console.log('JSON Server is running')
})

// In this example, returned resources will be wrapped in a body property
router.render = (req, res) => {
    res.jsonp({
      data: res.locals.data
    })
  }
```

**Pull request closed without merging**
