### PR TITLE
V3

### PR DESCRIPTION
**Pull request by defli**

### CODE REVIEW

**Comment by typicode** [comment]
Hi, Sorry for the delay and thanks for the PR.
Just wanted to say that I think the idea is really cool but not sure yet how to integrate it into the project.

**Comment by defli** [comment]
I am so sorry, it was my development environment. I sent pull request by mistake. It wasn't final code. I have some idea, If I will find time, I wanna implement some features.

**Comment by defli** [comment]
I want to embed relational data to json. Maybe syntax will be _embed=users and If I want to multiple relationship it will be _embed=users, items

What is your opinion about this feature?

**Comment by typicode** [comment]
No worries about that. I'm happy to have seen your idea :)
Right now, I don't have much opinions about the syntax. But in any case, it will be easy to modify afterwards.

I like the feature, if you can add some basic tests it'll be good.
Does the code already work?

If you need some help also do not hesitate to ask.

**Comment by defli** [comment]
Thanks. Yes, it works. But it needs some modifications and optimizations. Ok, I will add tests. I will send pull request when I finish it.

**Pull request closed without merging**
