### PR TITLE
Update README.md - Updated documentation regarding pagination API from per_page to _limit

### PR DESCRIPTION
**Pull request by ZynthCode**
Updated documentation regarding pagination API from per_page to _limit

### CODE REVIEW

**Comment by ZynthCode** [comment]
I spent probably 10-30 minutes scratching my head trying to figure out why _page_size or page_size did not work, only to dig deeper and find it is now named _limit 😅

**Comment by typicode** [comment]
_per_page should work, otherwise it's a bug.

_limit should be used with _start and _end.

**Comment by ZynthCode** [comment]
> Thank you for the PR.
> 
> _per_page should work, otherwise it's a bug.
> 
> _limit should be used with _start.

This was tested on https://jsonplaceholder.typicode.com/posts?_page=1&_limit=5

To achieve pagination I had to use **_page** with **_limit**, since _per_page does not currently work there, test: https://jsonplaceholder.typicode.com/posts?_page=1&_per_page=5

If the jsonplaceholder.typicode.com is not up to date, or does not reflect the changes on this repository, I suspect you can close this as a non-issue. 😺

**Comment by typicode** [comment]
It's running 0.17and will continue to do so to avoid breaking stuff.

Closing then 👍

**Pull request closed without merging**
