### PR TITLE
Added _limit param. 

### PR DESCRIPTION
**Pull request by binali-rustamov**
Example usage: _start=2&_limit=3 alternative to _start=2&_end=5.
I need _limit param for my ExtJS application. =)

### CODE REVIEW

**Comment by typicode** [comment]
Hi,
Good addition :)
Could you please fix the indentation (2 spaces instead of 4) as it makes hard to see the changes?

BTW, you don't have to worry about the end of slice:

```javascript
[1, 2, 3].slice(1, 1000) // [2, 3]
```

**Comment by binali-rustamov** [comment]
Hello my friend.
I use WebStorm with default settings)
I'll change this indent settings now.
About end of slice. Ok, I agree with you.

One moment. I'll fix all of that. =)

**Comment by binali-rustamov** [comment]
My friend... How it now? It's ok? Merge man! Merge man! xD

**Comment by binali-rustamov** [comment]
I can't understand what's with Travis CI...

**Comment by binali-rustamov** [comment]
up!

**Comment by typicode** [comment]
Guess it was a temporary issue with Travis CI
Thanks :+1:

**Pull request merged**
