### PR TITLE
FIXED #135 generate.js with watch

### LINKED ISSUE #135: [feature request] --watch with generate.js
would be nice if --watch option would play nicely with 
javascript file `generate.js` to generate mocks.

watch currently only works with static `json.db` files

### PR DESCRIPTION
**Pull request by syzer**

### CODE REVIEW

**Comment by typicode** [comment]
Thanks :)

**Comment by goodpixels** [comment]
either i am doing something wrong, or this is still not working properly.

here's a sample `api.js` file:

```
module.exports = function() {

	var data = {

		posts: [

			{ id: 3, name: 'test' },
			{ id: 6, name: 'another test' },

		]

	}

	return data;

}
```

and i'm running the server with:

```
json-server -w api.js
```

this works fine. but whenever i make a change to the `api.js` file, the server doesn't reload the API.

so, updating `api.js` to something like this:

```
module.exports = function() {

	var data = {

		me: {

			id: 182,
			name: 'John Doe',

		},

		posts: [

			{ id: 3, name: 'test' },
			{ id: 6, name: 'another test' },

		]

	}

	return data;

}
```

is not working properly. the server picks up the change and lists a new endpoint in the terminal, but i can't access that url. here's the output from the terminal:

```

  \{^_^}/ hi!

  Loading api.js
  Done

  Resources
  http://localhost:3000/posts

  Home
  http://localhost:3000

  Watching...

GET /posts 200 8.368 ms - 92
  api.js has changed, reloading...

  Loading api.js
  Done

  Resources
  http://localhost:3000/me
  http://localhost:3000/posts

  Home
  http://localhost:3000

GET /me 404 1.059 ms - -
```

see the 404? the funny thing is that if i restart the server without changing `api.js` the route will be working just fine. is it me or is this a bug?

**Comment by syzer** [comment]
the core was rewritten since this fix...
i'll check and get back to you, ok?

**Comment by syzer** [comment]
apparently after rewrite we lost (watch for generate.js) feature :(
maybe i will able to hack id this evening

**Pull request merged**
